// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ase.poi.domain;

import com.ase.poi.domain.PointOfInterest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PointOfInterest_Roo_Configurable {
    
    declare @type: PointOfInterest: @Configurable;
    
}
